export { default as App } from './App';
export { default as SignIn } from './SignIn/SignIn';
export { default as Register } from './Register/Register';
export { default as CmpsPage } from './Competitions/CmpsPage';;
export { default as TeamsPage } from './Teams/TeamsPage';
export { default as ConfDialog } from './ConfDialog/ConfDialog';
export { default as EntryDialog } from './ConfDialog/EntryDialog';
export { default as CmpPage } from './Competitions/CmpPage';
export { default as InstructionsPage } from './Competitions/InstructionsPage';
